apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kimai2-mariadb-pvc
  namespace: kimai2
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
  finalizers:
    - kubernetes.io/pvc-protection
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: kimai2-mariadb-pv
  storageClassName: kimai2-mariadb-azure-storage-class
  volumeMode: Filesystem
