apiVersion: v1
kind: PersistentVolume
metadata:
  name: kimai2-mariadb-pv
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  finalizers:
    - kubernetes.io/pv-protection
    - external-attacher/disk-csi-azure-com
spec:
  capacity:
    storage: 4Gi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: >-
      /subscriptions/5cd41c92-754a-486e-95ff-f1fc311c0fa2/resourceGroups/SmartconX-UAT-RG/providers/Microsoft.Compute/disks/kimai-mariadb-pv
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kimai2-mariadb-azure-storage-class
  volumeMode: Filesystem
